local colors = {}

colors = {
    none = "NONE",

    Front = '#D4D4D4',
    Back = '#1E1E1E',

    TabCurrent = '#282C34',
    TabOther = '#7B7B7F',
    TabOutside = '#252526',

    LeftDark = '#252526',
    LeftMid = '#373737',
    LeftLight = '#636369',

    PopupFront = '#BBBBBB',
    PopupBack = '#272727',
    PopupHighlightBlue = '#004b72',
    PopupHighlightGray = '#343B41',

    SplitLight = '#898989',
    SplitDark = '#444444',
    SplitThumb = '#424242',

    CursorDarkDark = '#222222',
    CursorDark = '#51504F',
    CursorLight = '#AEAFAD',
    Selection = '#264F78',
    LineNumber = '#5A5A5A',
    CursorLineNumber = '#FCEE0B',

    DiffRedDark = '#4B1818',
    DiffRedLight = '#6F1313',
    DiffRedLightLight = '#FB0101',
    DiffGreenDark = '#373D29',
    DiffGreenLight = '#4B5632',
    SearchCurrent = '#515c6a',
    Search = '#613315',
    SearchY = '#FCEE0B',

    Context = '#404040',
    ContextChar = '#FCEE0B',
    ContextCurrent = '#707070',

    FoldBackground = '#202d39',

    -- Syntax colors
    Gray = '#808080',
    Violet = '#646695',
    Blue = '#569CD6',
    DarkBlue = '#223E55',
    MediumBlue = '#18a2fe',
    LightBlue = '#9CDCFE',
    Green = '#6A9955',
    BlueGreen = '#4EC9B0',
    LightGreen = '#B5CEA8',
    Red = '#F44747',
    Orange = '#CE9178',
    LightRed = '#D16969',
    YellowOrange = '#D7BA7D',
    Yellow = '#DCDCAA',
    Pink = '#C586C0',


    UiBlue = '#084671',
    UiOrange = '#f28b25',


    error = "#C53334",
    warning = "#DBB365",
    info = "#6893CA",
    hint = "#1ABC9C",
}

    -- __vscode_foreground = "#CCCCCC",
    -- __vscode_background = "#1E1E1E",
    -- __vscode_local_background = "#252526",
    -- __vscode_visual_color = "#264F78",
    -- __vscode_replace_search_color = "#613214",
    -- __vscode_window_spearator_color = "#454545",
    -- __vscode_extra_decorate_color = "#4FC1FF",
    -- __vscode_inactive_symbol_line_foreground = "#858585",
    -- __vscode_onaction_symbol_line_foreground = "#C6C6C6",
    -- __vscode_onaction_cursor_line_background = "#37373D",
    -- __vscode_fold_background = "#202D39",
    -- __vscode_nontext_foreground = "#3D3E3D",
    -- __vscode_statusline_background = "#007ACC",
    -- __vscode_statusline_foreground = "#FFFFFF",
    -- __vscode_other_word_highlight_background = "#474747",
    -- __vscode_winbar_foreground = "#969696",
    -- __vscode_diff_add_foreground = "#487E02",
    -- __vscode_diff_del_foreground = "#F14C4C",
    -- __vscode_diff_change_foreground = "#1B7CA2",
    -- __vscode_diff_text_foreground = "#9CDCFE",
    -- __vscode_diff_text_background = "#4B592B",
    -- __vscode_todo_foreground = "#1F1F1F",
    -- __vscode_todo_background = "#D9D9D9",
    -- __vscode_variable = "#D4D4D4",
    -- __vscode_keyword = "#569CD6",
    -- __vscode_strings = "#CE9178",
    -- __vscode_comment = "#6A9955",
    -- __vscode_methods = "#DCDCAA",
    -- __vscode_type = "#4EC9B0",
    -- __vscode_file = "#9CDCFE",
    -- __vscode_head = "#C586C0",
    -- __vscode_number = "#B5CEA8",
    -- __vscode_define_foreground = "#B4B4B4",
    -- __vscode_tag_foreground = "#D09E4C",
    -- __vsocode_tag_warpper_foreground = "#808080",
    -- __vscode_typescript_type_foreground = "#B5D4A0",
    -- __vscode_lsp_hint = "#00B7E4",
    -- __vscode_lsp_info = "#3794ff",
    -- __vscode_lsp_warn = "#CCA700",
    -- __vscode_lsp_error = "#F14C4C",
    -- __vscode_inactive_indent_guide_background = "#404040",
    -- __vscode_onactive_indent_guide_background = "#707070",
    -- __vscode_inactive_table_background = "#2D2D2D",
    -- __vscode_inactive_table_foreground = "#969696",
    -- __vscode_onactive_table_background = "#1E1E1E",
    -- __vscode_onactive_table_foreground = "#FFFFFF",
    -- __vscode_local_completion_scrollview_background = "#464647",
    -- __vscode_local_completion_selected_background = "#04395E",
    -- __vscode_global_window_scrollview_background = "#424242",
    -- __vscode_tree_icons_foreground = "#90A4AE",
    -- __vscode_tree_fonts_foreground = "#CCCCCC",
    -- __vscode_git_rename_foreground = "#73C991",
    -- __vscode_git_modified_foreground = "#CCA700",
    -- __vscode_git_added_foreground = "#73C991",
    -- __vscode_git_ignore_foreground = "#8C8C8C",
    -- __vscode_git_stage_modified_foreground = "#E2C08D",
    -- __vscode_git_stage_deleted_foreground = "#C74E39",
    -- __vscode_bracket_level_01_foreground = "#FFD700",
    -- __vscode_bracket_level_02_foreground = "#DA70D6",
    -- __vscode_bracket_level_03_foreground = "#179FFF",

return colors
